/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.webots.mydsl.myDsl.Escape;
import org.xtext.webots.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Escape</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EscapeImpl extends BehaviorImpl implements Escape
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected EscapeImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return MyDslPackage.Literals.ESCAPE;
	}

} //EscapeImpl
