/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.webots.mydsl.myDsl.LeftMotor;
import org.xtext.webots.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Left Motor</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LeftMotorImpl extends ActuatorImpl implements LeftMotor
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected LeftMotorImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return MyDslPackage.Literals.LEFT_MOTOR;
	}

} //LeftMotorImpl
