/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.webots.mydsl.myDsl.MyDslPackage;
import org.xtext.webots.mydsl.myDsl.RightMotor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Right Motor</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RightMotorImpl extends ActuatorImpl implements RightMotor
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected RightMotorImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return MyDslPackage.Literals.RIGHT_MOTOR;
	}

} //RightMotorImpl
