/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.webots.mydsl.myDsl.MyDslFactory;
import org.xtext.webots.mydsl.myDsl.Robot;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RobotTest extends TestCase {

	/**
	 * The fixture for this Robot test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Robot fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RobotTest.class);
	}

	/**
	 * Constructs a new Robot test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RobotTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Robot test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Robot fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Robot test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Robot getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MyDslFactory.eINSTANCE.createRobot());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RobotTest
