/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Behavior#getSensors <em>Sensors</em>}</li>
 * </ul>
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getBehavior()
 * @model
 * @generated
 */
public interface Behavior extends EObject
{
  /**
	 * Returns the value of the '<em><b>Sensors</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.webots.mydsl.myDsl.Sensor}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Sensors</em>' containment reference list.
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getBehavior_Sensors()
	 * @model containment="true"
	 * @generated
	 */
  EList<Sensor> getSensors();

} // Behavior
