/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Distance Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getDistanceSensor()
 * @model
 * @generated
 */
public interface DistanceSensor extends Sensor
{
} // DistanceSensor
