/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Escape</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getEscape()
 * @model
 * @generated
 */
public interface Escape extends Behavior
{
} // Escape
