/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Motor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getLeftMotor()
 * @model
 * @generated
 */
public interface LeftMotor extends Actuator
{
} // LeftMotor
