/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Light Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getLightSensor()
 * @model
 * @generated
 */
public interface LightSensor extends Sensor
{
} // LightSensor
