/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mission</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Mission#isFinished <em>Finished</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Mission#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Mission#getBehaviors <em>Behaviors</em>}</li>
 * </ul>
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getMission()
 * @model
 * @generated
 */
public interface Mission extends EObject
{
  /**
	 * Returns the value of the '<em><b>Finished</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Finished</em>' attribute.
	 * @see #setFinished(boolean)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getMission_Finished()
	 * @model
	 * @generated
	 */
  boolean isFinished();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.Mission#isFinished <em>Finished</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Finished</em>' attribute.
	 * @see #isFinished()
	 * @generated
	 */
  void setFinished(boolean value);

  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getMission_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.Mission#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Behaviors</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.webots.mydsl.myDsl.Behavior}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Behaviors</em>' containment reference list.
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getMission_Behaviors()
	 * @model containment="true"
	 * @generated
	 */
  EList<Behavior> getBehaviors();

} // Mission
