/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.webots.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "myDsl";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.xtext.org/webots/mydsl/MyDsl";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "myDsl";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  MyDslPackage eINSTANCE = org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.RobotConfigurationImpl <em>Robot Configuration</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.RobotConfigurationImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRobotConfiguration()
	 * @generated
	 */
  int ROBOT_CONFIGURATION = 0;

  /**
	 * The feature id for the '<em><b>MAX SPEED</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_CONFIGURATION__MAX_SPEED = 0;

  /**
	 * The feature id for the '<em><b>TIME STEP</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_CONFIGURATION__TIME_STEP = 1;

  /**
	 * The feature id for the '<em><b>Robot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_CONFIGURATION__ROBOT = 2;

  /**
	 * The feature id for the '<em><b>Mission</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_CONFIGURATION__MISSION = 3;

  /**
	 * The number of structural features of the '<em>Robot Configuration</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_CONFIGURATION_FEATURE_COUNT = 4;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.ActuatorImpl <em>Actuator</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.ActuatorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getActuator()
	 * @generated
	 */
  int ACTUATOR = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTUATOR__NAME = 0;

  /**
	 * The number of structural features of the '<em>Actuator</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTUATOR_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.BehaviorImpl <em>Behavior</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.BehaviorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getBehavior()
	 * @generated
	 */
  int BEHAVIOR = 2;

  /**
	 * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BEHAVIOR__SENSORS = 0;

  /**
	 * The number of structural features of the '<em>Behavior</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BEHAVIOR_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.SensorImpl <em>Sensor</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.SensorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getSensor()
	 * @generated
	 */
  int SENSOR = 3;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SENSOR__NAME = 0;

  /**
	 * The number of structural features of the '<em>Sensor</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SENSOR_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.RobotImpl <em>Robot</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.RobotImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRobot()
	 * @generated
	 */
  int ROBOT = 4;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT__NAME = 0;

  /**
	 * The feature id for the '<em><b>Actuators</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT__ACTUATORS = 1;

  /**
	 * The number of structural features of the '<em>Robot</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ROBOT_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.MissionImpl <em>Mission</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.MissionImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getMission()
	 * @generated
	 */
  int MISSION = 5;

  /**
	 * The feature id for the '<em><b>Finished</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MISSION__FINISHED = 0;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MISSION__NAME = 1;

  /**
	 * The feature id for the '<em><b>Behaviors</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MISSION__BEHAVIORS = 2;

  /**
	 * The number of structural features of the '<em>Mission</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MISSION_FEATURE_COUNT = 3;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.LeftMotorImpl <em>Left Motor</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.LeftMotorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getLeftMotor()
	 * @generated
	 */
  int LEFT_MOTOR = 6;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LEFT_MOTOR__NAME = ACTUATOR__NAME;

  /**
	 * The number of structural features of the '<em>Left Motor</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LEFT_MOTOR_FEATURE_COUNT = ACTUATOR_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.RightMotorImpl <em>Right Motor</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.RightMotorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRightMotor()
	 * @generated
	 */
  int RIGHT_MOTOR = 7;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RIGHT_MOTOR__NAME = ACTUATOR__NAME;

  /**
	 * The number of structural features of the '<em>Right Motor</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RIGHT_MOTOR_FEATURE_COUNT = ACTUATOR_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.EscapeImpl <em>Escape</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.EscapeImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getEscape()
	 * @generated
	 */
  int ESCAPE = 8;

  /**
	 * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ESCAPE__SENSORS = BEHAVIOR__SENSORS;

  /**
	 * The number of structural features of the '<em>Escape</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ESCAPE_FEATURE_COUNT = BEHAVIOR_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.HomeImpl <em>Home</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.HomeImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getHome()
	 * @generated
	 */
  int HOME = 9;

  /**
	 * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int HOME__SENSORS = BEHAVIOR__SENSORS;

  /**
	 * The number of structural features of the '<em>Home</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int HOME_FEATURE_COUNT = BEHAVIOR_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.DistanceSensorImpl <em>Distance Sensor</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.DistanceSensorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getDistanceSensor()
	 * @generated
	 */
  int DISTANCE_SENSOR = 10;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DISTANCE_SENSOR__NAME = SENSOR__NAME;

  /**
	 * The number of structural features of the '<em>Distance Sensor</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DISTANCE_SENSOR_FEATURE_COUNT = SENSOR_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.webots.mydsl.myDsl.impl.LightSensorImpl <em>Light Sensor</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.webots.mydsl.myDsl.impl.LightSensorImpl
	 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getLightSensor()
	 * @generated
	 */
  int LIGHT_SENSOR = 11;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LIGHT_SENSOR__NAME = SENSOR__NAME;

  /**
	 * The number of structural features of the '<em>Light Sensor</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LIGHT_SENSOR_FEATURE_COUNT = SENSOR_FEATURE_COUNT + 0;


  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration <em>Robot Configuration</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Robot Configuration</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RobotConfiguration
	 * @generated
	 */
  EClass getRobotConfiguration();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMAX_SPEED <em>MAX SPEED</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>MAX SPEED</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMAX_SPEED()
	 * @see #getRobotConfiguration()
	 * @generated
	 */
  EAttribute getRobotConfiguration_MAX_SPEED();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getTIME_STEP <em>TIME STEP</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>TIME STEP</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RobotConfiguration#getTIME_STEP()
	 * @see #getRobotConfiguration()
	 * @generated
	 */
  EAttribute getRobotConfiguration_TIME_STEP();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getRobot <em>Robot</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Robot</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RobotConfiguration#getRobot()
	 * @see #getRobotConfiguration()
	 * @generated
	 */
  EReference getRobotConfiguration_Robot();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMission <em>Mission</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Mission</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMission()
	 * @see #getRobotConfiguration()
	 * @generated
	 */
  EReference getRobotConfiguration_Mission();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Actuator <em>Actuator</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Actuator</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Actuator
	 * @generated
	 */
  EClass getActuator();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.Actuator#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Actuator#getName()
	 * @see #getActuator()
	 * @generated
	 */
  EAttribute getActuator_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Behavior <em>Behavior</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Behavior</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Behavior
	 * @generated
	 */
  EClass getBehavior();

  /**
	 * Returns the meta object for the containment reference list '{@link org.xtext.webots.mydsl.myDsl.Behavior#getSensors <em>Sensors</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Sensors</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Behavior#getSensors()
	 * @see #getBehavior()
	 * @generated
	 */
  EReference getBehavior_Sensors();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Sensor <em>Sensor</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Sensor</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Sensor
	 * @generated
	 */
  EClass getSensor();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.Sensor#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Sensor#getName()
	 * @see #getSensor()
	 * @generated
	 */
  EAttribute getSensor_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Robot <em>Robot</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Robot</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Robot
	 * @generated
	 */
  EClass getRobot();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.Robot#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Robot#getName()
	 * @see #getRobot()
	 * @generated
	 */
  EAttribute getRobot_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link org.xtext.webots.mydsl.myDsl.Robot#getActuators <em>Actuators</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Actuators</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Robot#getActuators()
	 * @see #getRobot()
	 * @generated
	 */
  EReference getRobot_Actuators();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Mission <em>Mission</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Mission</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Mission
	 * @generated
	 */
  EClass getMission();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.Mission#isFinished <em>Finished</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Finished</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Mission#isFinished()
	 * @see #getMission()
	 * @generated
	 */
  EAttribute getMission_Finished();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.webots.mydsl.myDsl.Mission#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Mission#getName()
	 * @see #getMission()
	 * @generated
	 */
  EAttribute getMission_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link org.xtext.webots.mydsl.myDsl.Mission#getBehaviors <em>Behaviors</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Behaviors</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Mission#getBehaviors()
	 * @see #getMission()
	 * @generated
	 */
  EReference getMission_Behaviors();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.LeftMotor <em>Left Motor</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Left Motor</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.LeftMotor
	 * @generated
	 */
  EClass getLeftMotor();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.RightMotor <em>Right Motor</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Right Motor</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.RightMotor
	 * @generated
	 */
  EClass getRightMotor();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Escape <em>Escape</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Escape</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Escape
	 * @generated
	 */
  EClass getEscape();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.Home <em>Home</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Home</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.Home
	 * @generated
	 */
  EClass getHome();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.DistanceSensor <em>Distance Sensor</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Distance Sensor</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.DistanceSensor
	 * @generated
	 */
  EClass getDistanceSensor();

  /**
	 * Returns the meta object for class '{@link org.xtext.webots.mydsl.myDsl.LightSensor <em>Light Sensor</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Light Sensor</em>'.
	 * @see org.xtext.webots.mydsl.myDsl.LightSensor
	 * @generated
	 */
  EClass getLightSensor();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  MyDslFactory getMyDslFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.RobotConfigurationImpl <em>Robot Configuration</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.RobotConfigurationImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRobotConfiguration()
		 * @generated
		 */
    EClass ROBOT_CONFIGURATION = eINSTANCE.getRobotConfiguration();

    /**
		 * The meta object literal for the '<em><b>MAX SPEED</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ROBOT_CONFIGURATION__MAX_SPEED = eINSTANCE.getRobotConfiguration_MAX_SPEED();

    /**
		 * The meta object literal for the '<em><b>TIME STEP</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ROBOT_CONFIGURATION__TIME_STEP = eINSTANCE.getRobotConfiguration_TIME_STEP();

    /**
		 * The meta object literal for the '<em><b>Robot</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ROBOT_CONFIGURATION__ROBOT = eINSTANCE.getRobotConfiguration_Robot();

    /**
		 * The meta object literal for the '<em><b>Mission</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ROBOT_CONFIGURATION__MISSION = eINSTANCE.getRobotConfiguration_Mission();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.ActuatorImpl <em>Actuator</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.ActuatorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getActuator()
		 * @generated
		 */
    EClass ACTUATOR = eINSTANCE.getActuator();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ACTUATOR__NAME = eINSTANCE.getActuator_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.BehaviorImpl <em>Behavior</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.BehaviorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getBehavior()
		 * @generated
		 */
    EClass BEHAVIOR = eINSTANCE.getBehavior();

    /**
		 * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference BEHAVIOR__SENSORS = eINSTANCE.getBehavior_Sensors();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.SensorImpl <em>Sensor</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.SensorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getSensor()
		 * @generated
		 */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.RobotImpl <em>Robot</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.RobotImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRobot()
		 * @generated
		 */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
		 * The meta object literal for the '<em><b>Actuators</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ROBOT__ACTUATORS = eINSTANCE.getRobot_Actuators();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.MissionImpl <em>Mission</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.MissionImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getMission()
		 * @generated
		 */
    EClass MISSION = eINSTANCE.getMission();

    /**
		 * The meta object literal for the '<em><b>Finished</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute MISSION__FINISHED = eINSTANCE.getMission_Finished();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute MISSION__NAME = eINSTANCE.getMission_Name();

    /**
		 * The meta object literal for the '<em><b>Behaviors</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MISSION__BEHAVIORS = eINSTANCE.getMission_Behaviors();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.LeftMotorImpl <em>Left Motor</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.LeftMotorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getLeftMotor()
		 * @generated
		 */
    EClass LEFT_MOTOR = eINSTANCE.getLeftMotor();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.RightMotorImpl <em>Right Motor</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.RightMotorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getRightMotor()
		 * @generated
		 */
    EClass RIGHT_MOTOR = eINSTANCE.getRightMotor();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.EscapeImpl <em>Escape</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.EscapeImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getEscape()
		 * @generated
		 */
    EClass ESCAPE = eINSTANCE.getEscape();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.HomeImpl <em>Home</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.HomeImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getHome()
		 * @generated
		 */
    EClass HOME = eINSTANCE.getHome();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.DistanceSensorImpl <em>Distance Sensor</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.DistanceSensorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getDistanceSensor()
		 * @generated
		 */
    EClass DISTANCE_SENSOR = eINSTANCE.getDistanceSensor();

    /**
		 * The meta object literal for the '{@link org.xtext.webots.mydsl.myDsl.impl.LightSensorImpl <em>Light Sensor</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.webots.mydsl.myDsl.impl.LightSensorImpl
		 * @see org.xtext.webots.mydsl.myDsl.impl.MyDslPackageImpl#getLightSensor()
		 * @generated
		 */
    EClass LIGHT_SENSOR = eINSTANCE.getLightSensor();

  }

} //MyDslPackage
