/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMAX_SPEED <em>MAX SPEED</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getTIME_STEP <em>TIME STEP</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMission <em>Mission</em>}</li>
 * </ul>
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobotConfiguration()
 * @model
 * @generated
 */
public interface RobotConfiguration extends EObject
{
  /**
	 * Returns the value of the '<em><b>MAX SPEED</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>MAX SPEED</em>' attribute.
	 * @see #setMAX_SPEED(String)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobotConfiguration_MAX_SPEED()
	 * @model
	 * @generated
	 */
  String getMAX_SPEED();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMAX_SPEED <em>MAX SPEED</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>MAX SPEED</em>' attribute.
	 * @see #getMAX_SPEED()
	 * @generated
	 */
  void setMAX_SPEED(String value);

  /**
	 * Returns the value of the '<em><b>TIME STEP</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>TIME STEP</em>' attribute.
	 * @see #setTIME_STEP(String)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobotConfiguration_TIME_STEP()
	 * @model
	 * @generated
	 */
  String getTIME_STEP();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getTIME_STEP <em>TIME STEP</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>TIME STEP</em>' attribute.
	 * @see #getTIME_STEP()
	 * @generated
	 */
  void setTIME_STEP(String value);

  /**
	 * Returns the value of the '<em><b>Robot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Robot</em>' containment reference.
	 * @see #setRobot(Robot)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobotConfiguration_Robot()
	 * @model containment="true"
	 * @generated
	 */
  Robot getRobot();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getRobot <em>Robot</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Robot</em>' containment reference.
	 * @see #getRobot()
	 * @generated
	 */
  void setRobot(Robot value);

  /**
	 * Returns the value of the '<em><b>Mission</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Mission</em>' containment reference.
	 * @see #setMission(Mission)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobotConfiguration_Mission()
	 * @model containment="true"
	 * @generated
	 */
  Mission getMission();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.RobotConfiguration#getMission <em>Mission</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Mission</em>' containment reference.
	 * @see #getMission()
	 * @generated
	 */
  void setMission(Mission value);

} // RobotConfiguration
