/**
 * generated by Xtext 2.22.0
 */
package org.xtext.webots.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Robot#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.webots.mydsl.myDsl.Robot#getActuators <em>Actuators</em>}</li>
 * </ul>
 *
 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobot()
 * @model
 * @generated
 */
public interface Robot extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobot_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.webots.mydsl.myDsl.Robot#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Actuators</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.webots.mydsl.myDsl.Actuator}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Actuators</em>' containment reference list.
	 * @see org.xtext.webots.mydsl.myDsl.MyDslPackage#getRobot_Actuators()
	 * @model containment="true"
	 * @generated
	 */
  EList<Actuator> getActuators();

} // Robot
